parameters:
#    bolsa_ofertas.example.class: Bolsa\OfertasBundle\Example

services:
#    bolsa_ofertas.example:
#        class: %bolsa_ofertas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
