security:
    
  firewalls:
    backend:
      pattern: ^/
      anonymous: ~
      form_login:
          login_path: login
          check_path: login_check
          default_target_path: /backend
      logout:
          path: /logout
          target: /
      
      
  access_control:
    - { path: ^/backend, roles: ROLE_ADMIN }
    
  providers:
    user_db:
            entity: { class: Bolsa\InscriptosBundle\Entity\Inscriptos, property: username }
    
  encoders:
    Bolsa\InscriptosBundle\Entity\Inscriptos:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10







