parameters:
#    bolsa_inscriptos.example.class: Bolsa\InscriptosBundle\Example

services:
#    bolsa_inscriptos.example:
#        class: %bolsa_inscriptos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
