<?php

namespace Bolsa\InscriptosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptosRepository extends EntityRepository
{
}
