parameters:
#    bolsa_backend.example.class: Bolsa\BackendBundle\Example

services:
#    bolsa_backend.example:
#        class: %bolsa_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
